### PR TITLE
Fixes #1 concurreny bug in remove listener

### LINKED ISSUE #1: concurrency bug in RemoveListener
https://github.com/tendermint/go-events/blob/master/events.go#L77

we're running `delete` on a map in an RLock. i think we can do the Rlock, check if the listener is nil, and if not do the normal Lock to delete

This caused a race condition that go paniced on, see https://github.com/eris-ltd/eris-db/issues/143

### PR DESCRIPTION
**Pull request by benjaminbollen**
Introduces five unit tests to assert expected behaviour of EventSwitch for events and listeners:
- TestAddListenerForEventFireOnce
- TestAddListenerForEventFireMany
- TestAddListenerForDifferentEvents
- TestAddDifferentListenerForDifferentEvents
- TestAddAndRemoveListener

and a sixth unit test that to explore the race condition reported by @dennismckinnon in https://github.com/eris-ltd/eris-db/issues/143 with `EventSwitch.RemoveListener()`:
- TestRemoveListenersAsync
This last test fails when run with race condition tracking enabled.

Secondly the race condition itself is addressed, by enforcing a full lock as proposed by @ebuchman in #1

### CODE REVIEW

File: events_test.go [hunk 1]
```diff
@@ -0,0 +1,335 @@
...
+	// after sending all event1, unsubscribe for all events
+	evsw.RemoveListener("listener")
+	go fireEvents(evsw, "event2", doneSending2, uint64(1001))
+	checkSumEvent2 := <-doneSending2
+	close(numbers1)
+	close(numbers2)
+	eventSum1 := <-doneSum1
+	eventSum2 := <-doneSum2
+	if checkSumEvent1 != eventSum1 ||
+		// correct value asserted by pre-seeding tests, suffices to be non-zero
```
Comment (benjaminbollen) [inline events_test.go]: I hate the autocomplete of my current IDE; "preceding"
